-  hosts: all
   remote_user: ec2-user
   become: yes
   tasks:
   - name: Install the latest version of docker
     yum:
       name: docker
       state: present
   - name: Create a docker container
     docker_container:
        name: tomcat_deploy
        image: myimage
        
